---
version: "3.9"

services:
  runner:
    build:
      context: docker
      network: host
    command: peertube-runner server
    network_mode: host
    user: "0"
    environment:
      NODE_OPTIONS: --use-openssl-ca
    volumes:
      - type: bind
        source: ./config.toml
        target: /root/.config/peertube-runner-nodejs/default/config.toml
      - type: bind
        source: ./docker/ffmpeg_wrapper.py
        target: /usr/local/bin/ffmpeg
      - './logs:/home/node/ffmpeg_wrapper_logs/'

# Register:
# docker compose exec -it --user 1000 runner peertube-runner register --url https://localhost.ru --registration-token ptrrt-1e9082fb-0575-411e-a618-fc771770e471 --runner-name my-runner-name
