version: 1

formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(thread)10d --- [%(threadName)15s] %(name)-30s : %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

loggers:
  root:
    level: DEBUG
    handlers: [ console ]

